### ISSUE TITLE
Broken link in /docs/preview.md

### ISSUE THREAD

**Issue by roblthegreat** [SenseNet/sn-preview#8]
In /docs/preview.md, near the bottom, is a link titled "How to integrate a custom document preview generator" which is broken and returns a 404.  The link points to https://github.com/SenseNet/sn-preview/blob/master/docs/custom-document-preview-generator.

I am not seeing a document called "custom-document-preview-generator" in this repo or on the Community site docs.

I did locate a version on the old 6.x wiki under http://wiki.sensenet.com/How_to_integrate_a_custom_document_preview_generator .

**Comment by daniloff200** [comment]
@herflis  hey!
is it still an issue, that I can pick? I also couldn't find such doc, but, maybe we should update it to link to the Wiki, or, remove that?

**Comment by herflis** [comment]
hey @daniloff200,
the best would be to port  [the old doc](http://wiki.sensenet.com/How_to_integrate_a_custom_document_preview_generator) from the Wiki to [this repo's doc folder](https://github.com/SenseNet/sn-preview/blob/master/docs) as _custom-document-preview-generator.md_

**Comment by daniloff200** [comment]
@herflis cool! Please, assign this to me then!

**Comment by Ishaan28malik** [comment]
Is this fixed @herflis ?

**Comment by herflis** [comment]
@Ishaan28malik yes, unfortunately it is almost fixed (the missing document is under review)

**Comment by daniloff200** [comment]
Well played @tacoelho

**Comment by Ishaan28malik** [comment]
Oh ok
@herflis

**Comment by herflis** [comment]
@daniloff200 , sorry I messed up things a bit, and did not remember that you were assigned to this issue before I reviewed the pr. Btw you earned the swag with your other pr already ☺️ But if you an @Ishaan28malik are both interested, we have many other docs to port from the wiki to the github. I try to add some new issues related during the weekend. ☝🏻

**Comment by daniloff200** [comment]
@herflis that's totally understandable, don't think, that  I am angry or disappointed 
I just want to help people with my knowledge and time, because,  it's OSS,  and we use it every day , and have to not only take from it, but help it too

Swag just a cool bonus and a good memories (and also it helps people to get info about the product, you can't imagine how many people asks  'wow,  cool TShirt,  but, what it the %companyName% ' 😎

**Comment by tacoelho** [comment]
> Well played @tacoelho

Sorry, I didn’t see anyone assigned when I took this issue to solve.
