### ISSUE TITLE
Comment OData API

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-preview#9]
Add actions for managing doc preview comments.

The content and the version is appointed by the OData resource (path and parameters).

#### GetPreviewComments
Required permissions: `Preview`

**Parameters**
- content version (in the url)
- page

**Response: comment json objects**
```json
[
	{
		"id": "abc-123",
		"createdBy": { 
                       "id": 22222,
                       "path": "/Root/IMS/Builtin/Portal/Somebody",
                       "username": "sn\\somebody",
                       "displayName": "Somebody",
                       "avatarUrl": "https://example.com/image.png"
                 },
		"creationDate": "2019-02-28T00:27:46.22Z",
		"text": "....",
		"page": 12,
		"x": 12,
		"y": 234
	}
]
```

#### AddPreviewComment
Required permissions: `Open`

**Parameters**
- content version (in the url)
- page
- coordinates (X, Y)
- text

**Response: comment json object**
See above.

#### DeletePreviewComment
Required permissions: `Open` 

**Parameters**
- content version (in the url)
- comment id

**Response: json object**
```json
{
   "modified": true
}
```
(true if the comment was really deleted, otherwise false)

**Comment by gallayl** [comment]
a minor remarks on **GetPreviewComments**: Is the creationDate an UTC date? Can we get it in a standard UTC string format? (e.g. ``2019-02-28T00:27:46.22Z``)

**Comment by tusmester** [comment]
> a minor remarks on **GetPreviewComments**: Is the creationDate an UTC date? Can we get it in a standard UTC string format? (e.g. `2019-02-28T00:27:46.22Z`)

Thanks, I corrected the sample above, the real action returns the date in a correct format ofc.

**Comment by B3zo0** [comment]
Can we have x and y values as doubles please?

**Comment by herflis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Comments in DocViewer](https://trello.com/c/H68guu6E/2-comments-in-docviewer)
